basic_settings:
  site_title: Clint Bird
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo.gif
  logo_width: 35

menu_settings:
  menu_items:
    - title: 'CV'
      url: '/cv.html'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Business'
      url: '/business/'
    - title: 'Digitalization'
      url: '/digitalization/'
    - title: 'Cooking'
      url: '/cooking/'
    - title: 'Stuff'
      url: '/stuff/'

footer_settings:
  logo_image: 
  logo_width: 100
  footer_tagline: 30 something year old digital / lean enthusiast and aspiring chef. 15+ years experience in operations, digitalization, cost reduction and project management.

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/me@clintbird.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact - Clint Bird'
  send_button_text: 'Send Message'

social_settings:
  fas fa-envelope_url: '/contact.html'
  fas fa-rss_url: 'https://www.clintbird.com/feed.xml'
  fab fa-linkedin_url: 'https://linkedin.com/in/clintjb'
  fab fa-lastfm_url: 'http://lastfm.com/user/clintjb'
  fab fa-github_url: 'https://github.com/clintjb'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#aeaeae'
  accent_color: '#676767'
  border_color: '#dddddd'
  overlay_background_color: '#676767'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
